import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Music from '../components/Music'
export default function Home() {
  return (
    <div >
      <Head>
        <title>ZIMO MUSIC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Music/>
      </main>
    </div>
  )
}
